version: '3'

services:

  app:
    build: ./app
    container_name: app
    command: bash -c "cd app/ && python3 main.py" 
    environment:
      PYTHONPATH: .
      DATABASE_URL: "postgresql+asyncpg://username:password@postgres:5432/postgres"
    volumes:
      - ./app/logs:/app/app/logs
    ports:
      - '8000:8000'
    restart: on-failure

  gateway:
    build: ./gateway
    ports:
      - "8005:80"
    depends_on:
      - app
    restart: on-failure