FROM python:3.9-slim 

WORKDIR /app

COPY requirements.txt ./

RUN apt-get update && apt-get install -y libpq-dev
RUN pip install -r requirements.txt

COPY ./app/ ./app


RUN pip install psycopg2-binary 

EXPOSE 8000

# Comando para iniciar o servidor FastAPI quando o contêiner for iniciado
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]